In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import classification_report


In [2]:
parkinsons_data = pd.read_csv("E:/FINALPROJECT DATASET/data.csv")

In [6]:
x=parkinsons_data.drop(columns=['name','status','RPDE','DFA','spread1','spread2','D2','PPE'],axis=1)
y=parkinsons_data['status']

In [7]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [8]:
scalar = StandardScaler()
scalar.fit(X_train)
X_train = scalar.transform(X_train)
X_test = scalar.transform(X_test)

In [9]:
model = svm.SVC(kernel='linear')
model.fit(X_train,Y_train)

    

SVC(kernel='linear')

In [10]:
from sklearn.metrics import accuracy_score
pred=model.predict(X_test)
print(accuracy_score(pred,Y_test))
print(classification_report(pred,Y_test))

0.8205128205128205
              precision    recall  f1-score   support

           0       0.50      0.57      0.53         7
           1       0.90      0.88      0.89        32

    accuracy                           0.82        39
   macro avg       0.70      0.72      0.71        39
weighted avg       0.83      0.82      0.83        39



In [11]:
pred = model.predict(X_test)
    # Assuming 1 is the positive class and 0 is the negative class
class_prediction = pred[0]
print(class_prediction)


1


In [6]:
model1=tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [7]:
model1.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [8]:
model1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               2176      
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 64)                8256      
                                                                 
 dropout_1 (Dropout)         (None, 64)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 65        
                                                                 
Total params: 10,497
Trainable params: 10,497
Non-trainable params: 0
_________________________________________________________________


In [9]:
from tensorflow.keras.callbacks import ModelCheckpoint
import os
model_path = 'C:/Users/HIMAJA/vscodeprojects/Medilab/neuralnetwork.h5'
model1.save(model_path)

checkpoint = ModelCheckpoint(model_path, monitor='val_accuracy', verbose=1, save_best_only=True, mode='max')


In [10]:
model1.fit(X_train, Y_train, epochs=50, batch_size=32, validation_data=(X_test, Y_test))

Epoch 1/50
5/5 [==============================] - 1s 72ms/step - loss: 0.6754 - accuracy: 0.5513 - val_loss: 0.6258 - val_accuracy: 0.8205
Epoch 2/50
5/5 [==============================] - 0s 10ms/step - loss: 0.5824 - accuracy: 0.7051 - val_loss: 0.5558 - val_accuracy: 0.8462
Epoch 3/50
5/5 [==============================] - 0s 11ms/step - loss: 0.5202 - accuracy: 0.7756 - val_loss: 0.5145 - val_accuracy: 0.8205
Epoch 4/50
5/5 [==============================] - 0s 12ms/step - loss: 0.4779 - accuracy: 0.8141 - val_loss: 0.4864 - val_accuracy: 0.8462
Epoch 5/50
5/5 [==============================] - 0s 11ms/step - loss: 0.4673 - accuracy: 0.8013 - val_loss: 0.4650 - val_accuracy: 0.8462
Epoch 6/50
5/5 [==============================] - 0s 10ms/step - loss: 0.4410 - accuracy: 0.8141 - val_loss: 0.4471 - val_accuracy: 0.8462
Epoch 7/50
5/5 [==============================] - 0s 10ms/step - loss: 0.4326 - accuracy: 0.8141 - val_loss: 0.4347 - val_accuracy: 0.8462
Epoch 8/50
5/5 [===========

In [11]:
pred=model1.predict(X_test)
binary_predictions = (pred > 0.5).astype(int)

# If your model outputs probabilities and you want actual class labels (0 or 1)
class_predictions = np.argmax(pred, axis=1)

# Print or use the predictions as needed
print(pred)
print(binary_predictions)
print(class_predictions)

2/2 [==============================] - 0s 10ms/step
[[0.98747647]
 [0.9999787 ]
 [0.99946326]
 [0.53365725]
 [0.8151476 ]
 [0.51410943]
 [0.19913548]
 [0.9999912 ]
 [0.9985836 ]
 [0.99999934]
 [0.7723366 ]
 [0.5075385 ]
 [0.25499728]
 [0.9999994 ]
 [0.46429446]
 [0.93011624]
 [0.8203836 ]
 [0.6208254 ]
 [0.4607603 ]
 [0.9666902 ]
 [0.87427294]
 [0.6348793 ]
 [0.5372154 ]
 [0.4200731 ]
 [0.01779822]
 [0.85422325]
 [0.39840347]
 [0.95482403]
 [0.9966082 ]
 [0.866781  ]
 [0.9971972 ]
 [0.77229875]
 [0.8556309 ]
 [0.26123145]
 [0.99946946]
 [0.5870033 ]
 [0.01994655]
 [0.99607897]
 [0.9980216 ]]
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0]


In [13]:
print(classification_report(Y_test,binary_predictions))

              precision    recall  f1-score   support

           0       0.78      0.88      0.82         8
           1       0.97      0.94      0.95        31

    accuracy                           0.92        39
   macro avg       0.87      0.91      0.89        39
weighted avg       0.93      0.92      0.92        39



In [14]:
pred

array([[0.98747647],
       [0.9999787 ],
       [0.99946326],
       [0.53365725],
       [0.8151476 ],
       [0.51410943],
       [0.19913548],
       [0.9999912 ],
       [0.9985836 ],
       [0.99999934],
       [0.7723366 ],
       [0.5075385 ],
       [0.25499728],
       [0.9999994 ],
       [0.46429446],
       [0.93011624],
       [0.8203836 ],
       [0.6208254 ],
       [0.4607603 ],
       [0.9666902 ],
       [0.87427294],
       [0.6348793 ],
       [0.5372154 ],
       [0.4200731 ],
       [0.01779822],
       [0.85422325],
       [0.39840347],
       [0.95482403],
       [0.9966082 ],
       [0.866781  ],
       [0.9971972 ],
       [0.77229875],
       [0.8556309 ],
       [0.26123145],
       [0.99946946],
       [0.5870033 ],
       [0.01994655],
       [0.99607897],
       [0.9980216 ]], dtype=float32)

In [12]:
from sklearn import svm
from joblib import dump

# Define the filename for the saved model
model_filename = 'svm.pkl'

# Dump the model to a pickle file
dump(model, model_filename)

print("Model saved to", model_filename)


Model saved to svm.pkl


In [3]:
x=parkinsons_data.drop(columns=['name','status'],axis=1)
y=parkinsons_data['status']


In [4]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=2)
scalar = StandardScaler()


In [5]:
scalar.fit(X_train)

StandardScaler()

In [6]:
X_train = scalar.transform(X_train)
X_test = scalar.transform(X_test)


In [7]:
model = svm.SVC(kernel='linear')
model.fit(X_train,Y_train)
pred=model.predict(X_test)


In [8]:
print(classification_report(pred,Y_test))


              precision    recall  f1-score   support

           0       0.62      0.71      0.67         7
           1       0.94      0.91      0.92        32

    accuracy                           0.87        39
   macro avg       0.78      0.81      0.79        39
weighted avg       0.88      0.87      0.88        39



In [9]:
input_data=[122.18800,128.61100,115.76500,0.00524,0.00004,0.00169,0.00203,0.00507,0.01613,0.14300,0.00855,0.00776,0.01433,0.02566,0.00839,23.16200,0.579597,0.733659,-6.439398,0.266392,2.079922,0.133867]

In [11]:
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
# std_data = scalar.transform(input_data_reshaped)
prediction = model.predict(input_data_reshaped)
if prediction[0] == 1:
    print(1)
else:
    print(0)

0


In [12]:
from joblib import dump

# Define the filename for the saved model
model_filename = 'svm_two.pkl'

# Dump the model to a pickle file
dump(model, model_filename)

print("Model saved to", model_filename)

Model saved to svm_two.pkl
